version: "3"

volumes:
  sisventas_local_postgres_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: sisventas_local_django
    container_name: sisventas_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
    ports:
      - "8000:8000"
  
  postgres:
    image: 'postgres:15'
    restart: always
    container_name: sisventas_local_postgres
    volumes:
      - sisventas_local_postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./.envs/.local/.postgres
