# Generated by Django 4.2.9 on 2024-02-16 03:20

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PerfilPersona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "tipo_persona",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Proveedor"), (2, "Cliente")],
                        default=2,
                        verbose_name="Tiopo de persona",
                    ),
                ),
                (
                    "nombre_persona",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de la persona"
                    ),
                ),
                (
                    "tipo_documento",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Cédula de ciudadanía"),
                            (2, "Tarjeta de idetidad"),
                            (3, "Cédula extranjería"),
                        ],
                        default=1,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "numero_docuento",
                    models.CharField(max_length=15, verbose_name="Numero de documento"),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True,
                        max_length=70,
                        null=True,
                        verbose_name="Direccion de residencia",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Telefono"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Correo electronico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Persona",
                "verbose_name_plural": "Personas",
            },
        ),
    ]
