# Generated by Django 4.2.9 on 2024-02-27 22:44

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="perfilpersona",
            managers=[
                ("perfil", django.db.models.manager.Manager()),
            ],
        ),
    ]
