# Generated by Django 4.2.9 on 2024-02-29 21:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_perfilpersona_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="perfilpersona",
            managers=[],
        ),
    ]
