# Generated by Django 4.2.9 on 2024-02-12 02:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("articulo", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "tipo_comprobante",
                    models.CharField(
                        choices=[(1, "Boleta"), (2, "Comprobante"), (3, "Ticket")],
                        default=1,
                        verbose_name="Tipo de compronbante",
                    ),
                ),
                (
                    "serie_comprobante",
                    models.CharField(
                        max_length=7, verbose_name="Serie de compronbante"
                    ),
                ),
                (
                    "numero_comprobante",
                    models.CharField(
                        max_length=10, verbose_name="Nunmero de compronbante"
                    ),
                ),
                ("impuesto", models.FloatField(verbose_name="Impuesto de la venta")),
                (
                    "estado",
                    models.PositiveBigIntegerField(
                        choices=[(2, "Activo"), (3, "Inactivo")],
                        default=2,
                        verbose_name="Estado de la venta",
                    ),
                ),
                (
                    "articulos",
                    models.ManyToManyField(
                        related_name="venta_articulos",
                        to="articulo.articulo",
                        verbose_name="Articulos",
                    ),
                ),
                (
                    "perfil_persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.perfilpersona",
                        verbose_name="Perfil persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
            },
        ),
        migrations.CreateModel(
            name="Ingreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "tipo_comprobante",
                    models.CharField(
                        choices=[(1, "Boleta"), (2, "Comprobante"), (3, "Ticket")],
                        default=1,
                        verbose_name="Tipo de compronbante",
                    ),
                ),
                (
                    "serie_comprobante",
                    models.CharField(
                        max_length=7, verbose_name="Serie de compronbante"
                    ),
                ),
                (
                    "numero_comprobante",
                    models.CharField(
                        max_length=10, verbose_name="Nunmero de compronbante"
                    ),
                ),
                ("impuesto", models.FloatField(verbose_name="Impuesto del ingreso")),
                (
                    "estado",
                    models.PositiveBigIntegerField(
                        choices=[(2, "Activo"), (3, "Inactivo")],
                        default=2,
                        verbose_name="Estado del ingreso",
                    ),
                ),
                (
                    "articulos",
                    models.ManyToManyField(
                        related_name="ingreso_articulos",
                        to="articulo.articulo",
                        verbose_name="Articulos",
                    ),
                ),
                (
                    "perfil_persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.perfilpersona",
                        verbose_name="Perfil persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingreso",
                "verbose_name_plural": "Ingresos",
            },
        ),
    ]
