# Generated by Django 4.2.9 on 2024-02-27 17:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("articulo", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetalleDeIngreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField(verbose_name="Cantidad")),
                (
                    "precio_compra",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Precio de compra",
                    ),
                ),
                (
                    "precio_venta",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Precio de venta",
                    ),
                ),
                (
                    "articulos",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articulo.articulo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Ingreso",
                "verbose_name_plural": "Detalle de Ingresos",
            },
        ),
        migrations.CreateModel(
            name="DetalleDeVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField(verbose_name="Cantidad")),
                (
                    "precio_compra",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Precio de compra",
                    ),
                ),
                (
                    "precio_venta",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Precio de venta",
                    ),
                ),
                (
                    "articulos",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articulo.articulo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Venta",
                "verbose_name_plural": "Detalle de Ventas",
            },
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "tipo_comprobante",
                    models.CharField(
                        choices=[(1, "Boleta"), (2, "Comprobante"), (3, "Ticket")],
                        default=1,
                        verbose_name="Tipo de compronbante",
                    ),
                ),
                (
                    "serie_comprobante",
                    models.CharField(
                        max_length=7, verbose_name="Serie de compronbante"
                    ),
                ),
                (
                    "numero_comprobante",
                    models.CharField(
                        max_length=10, verbose_name="Nunmero de compronbante"
                    ),
                ),
                ("impuesto", models.FloatField(verbose_name="Impuesto de la venta")),
                (
                    "descuento",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="Descuento de la venta",
                    ),
                ),
                (
                    "estado",
                    models.PositiveBigIntegerField(
                        choices=[(2, "Activo"), (3, "Inactivo")],
                        default=2,
                        verbose_name="Estado de la venta",
                    ),
                ),
                (
                    "articulos",
                    models.ManyToManyField(
                        through="compra_venta.DetalleDeVenta",
                        to="articulo.articulo",
                        verbose_name="Articulos",
                    ),
                ),
                (
                    "perfil_persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.perfilpersona",
                        verbose_name="Perfil persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
            },
        ),
        migrations.CreateModel(
            name="Ingreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "tipo_comprobante",
                    models.SmallIntegerField(
                        choices=[(1, "Boleta"), (2, "Comprobante"), (3, "Ticket")],
                        default=1,
                        verbose_name="Tipo de compronbante",
                    ),
                ),
                (
                    "serie_comprobante",
                    models.CharField(
                        max_length=7, verbose_name="Serie de compronbante"
                    ),
                ),
                (
                    "numero_comprobante",
                    models.CharField(
                        max_length=10, verbose_name="Nunmero de compronbante"
                    ),
                ),
                ("impuesto", models.FloatField(verbose_name="Impuesto del ingreso")),
                (
                    "estado",
                    models.PositiveBigIntegerField(
                        choices=[(2, "Activo"), (3, "Inactivo")],
                        default=2,
                        verbose_name="Estado del ingreso",
                    ),
                ),
                (
                    "articulos",
                    models.ManyToManyField(
                        through="compra_venta.DetalleDeIngreso",
                        to="articulo.articulo",
                        verbose_name="Articulos",
                    ),
                ),
                (
                    "perfil_persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.perfilpersona",
                        verbose_name="Perfil persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingreso",
                "verbose_name_plural": "Ingresos",
            },
        ),
        migrations.AddField(
            model_name="detalledeventa",
            name="ventas",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="compra_venta.venta",
            ),
        ),
        migrations.AddField(
            model_name="detalledeingreso",
            name="ingresos",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="compra_venta.ingreso",
            ),
        ),
    ]
