# Generated by Django 4.2.9 on 2024-02-29 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compra_venta", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detalledeventa",
            name="precio_venta",
        ),
        migrations.AddField(
            model_name="detalledeventa",
            name="descuento",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Descuento",
            ),
        ),
        migrations.AlterField(
            model_name="detalledeingreso",
            name="cantidad",
            field=models.IntegerField(blank=True, verbose_name="Cantidad"),
        ),
        migrations.AlterField(
            model_name="detalledeingreso",
            name="precio_compra",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Precio de compra",
            ),
        ),
        migrations.AlterField(
            model_name="detalledeingreso",
            name="precio_venta",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Precio de venta",
            ),
        ),
        migrations.AlterField(
            model_name="detalledeventa",
            name="cantidad",
            field=models.IntegerField(blank=True, verbose_name="Cantidad"),
        ),
        migrations.AlterField(
            model_name="detalledeventa",
            name="precio_compra",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Precio de compra",
            ),
        ),
        migrations.AlterField(
            model_name="ingreso",
            name="impuesto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Impuesto del ingreso",
            ),
        ),
    ]
