# Generated by Django 4.2.9 on 2024-03-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compra_venta", "0002_remove_detalledeventa_precio_venta_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detalledeventa",
            name="precio_compra",
        ),
        migrations.RemoveField(
            model_name="venta",
            name="descuento",
        ),
        migrations.AddField(
            model_name="detalledeventa",
            name="precio_venta",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Precio de venta",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="total_venta",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="Total de la venta",
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="tipo_comprobante",
            field=models.SmallIntegerField(
                choices=[(1, "Boleta"), (2, "Comprobante"), (3, "Ticket")],
                default=1,
                verbose_name="Tipo de compronbante",
            ),
        ),
    ]
