# Generated by Django 4.2.9 on 2024-03-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compra_venta", "0003_remove_detalledeventa_precio_compra_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="impuesto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Impuesto de la venta",
            ),
        ),
    ]
