name: CONTINUOS INTEGRATION

on:
  pull_request:
    branches: [ "*" ]
    paths-ignore: [ "docs/**" ]

  push:
    branches: [ "*" ]
    paths-ignore: [ "docs/**" ]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: pip
          cache-dependency-path: |
            requirements.txt

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: estilos
        run: black --check .

      - name: revisión de imports
        run: isort . --check

      - name: revisión de resaltado
        run: flake8
