name: CONTINUOUS INTEGRATION

on:
  pull_request:
    branches: [ "*" ]
    paths-ignore: [ "docs/**" ]

  push:
    branches: [ "*" ]
    paths-ignore: [ "docs/**" ]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Build the Stack
        run:  docker-compose -f local.yml build

      - name: Run DB Migrations
        run:  docker-compose -f local.yml run --rm django python manage.py migrate

      - name: estilos
        run: black --check .

      - name: revisión de imports
        run: isort . --check

      - name: revisión de resaltado
        run: flake8

      - name: Pruebas unitarias
        run:  docker-compose -f local.yml run django pytest
