# Generated by Django 4.2.9 on 2024-02-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articulo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="descripcion",
            field=models.CharField(
                max_length=500, verbose_name="Descripcion de la categoria"
            ),
        ),
    ]
